# Regenerated by .github/workflows/release.yml on every tagged release, so the
# version and checksums below always match the published assets.
#
# The published asset is a Nuitka standalone build: compiled, so there is no
# interpreter and no readable source on disk. It is deliberately not a Nuitka
# *onefile* binary — onefile unpacks its whole payload on every single run, which
# adds seconds to something as small as `git-tidy --help`. The directory form
# does not unpack anything and starts immediately.
class GitTidy < Formula
  desc "Keep a directory full of git checkouts clean: sync, prune, clean, sweep"
  homepage "https://github.com/sapn95/git-tidy"
  version "1.0.3"
  license "MIT"

  on_macos do
    on_intel do
      # No Intel Mac binary is published; say so instead of failing later with a
      # missing url.
      odie "git-tidy ships macOS binaries for Apple silicon only; run ./git_tidy.py from a checkout"
    end

    on_arm do
      url "https://github.com/sapn95/git-tidy/releases/download/v1.0.3/git-tidy-macos-arm64.tar.gz"
      sha256 "1e7c9d3d0eede4d0fb1af393f873e9fccf787a913f0461678998d5db96c57f0f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sapn95/git-tidy/releases/download/v1.0.3/git-tidy-linux-arm64.tar.gz"
      sha256 "712a09b7ba5c255eb3fc63bc6f3516953f0c9d36aa9f0ff5df0552f67c40733b"
    end
    on_intel do
      url "https://github.com/sapn95/git-tidy/releases/download/v1.0.3/git-tidy-linux-x86_64.tar.gz"
      sha256 "bb03e56d4839e504a48cd529cd85b92f8ed9c7184cd1dcc7086b1799a93b94d6"
    end
  end

  def install
    # Before libexec.install, which would otherwise sweep the man page in with
    # everything else. git intercepts `git tidy --help` and looks for a man page
    # rather than passing the flag through, so one has to be where man finds it.
    man1.install "git-tidy.1" if File.exist?("git-tidy.1")
    libexec.install Dir["*"]
    bin.install_symlink libexec/"git-tidy"
  end

  test do
    assert_match "git-tidy #{version}", shell_output("#{bin}/git-tidy --version")
  end
end
